### ISSUE TITLE
Using cardstack with Theme Inheritance

### ISSUE THREAD

**Issue by zeigerpuppy** [khanduras/grav-theme-cardstack#12]
I am trying to use inheritance with cardstack to modify some elements for a particular site (removing dates from cards).
I have followed the instructions here: https://getgrav.org/blog/theme-development-with-inheritance

The inheritance works, but the cards are now arranged with only one card per row.

I am wondering if there's something else that needs to be edited for inheritance to work.

here are the modifications I made

```
mkdir themes/cardstack-child
```

in that dir, I created `cardstack-child.yaml` and tried to keep everything similar to the parent file apart from the `prefixes` lines:
```yaml
enabled: true
cardstack_route: '/cards'
default_lang: en
continueLinkIcon: 'exclamation-circle'

cardview:
  columns:
    small: 1
    medium: 2
    large: 3
    xlarge: 3

streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/cardstack-child
         - user/themes/cardstack
```

I then enabled the theme in `/config/system.yaml`

To debug, I tried copying over files from the parent theme systematically, but even will all the files copied over the cards are still in one row.  I'm wondering if there may be a hard coded css path or something that requires the theme folder to be called `cardstack`?
