### ISSUE TITLE
Card not showing - Grav v1.7.43 - Admin v1.10.43 - Cardstack v1.1.3

### ISSUE THREAD

**Issue by Snoozy01** [khanduras/grav-theme-cardstack#21]
Thank you for this theme that looks very good.

Starting from a fresh Grav install and Theme installed from admin, I'm trying to make it working with the demo pages and have tried to apply all README guidance and few issues / fixes but in the best case, I have a menu : "Index Cards" and a blank page with both Index and Cards.

Then when I add the following to default.md of 01.front_page folder, I got either a blank page either some html codes depending the default theme applied between Cardstack and Quark theme.
```
---
title: Index
cards:
    items:
        '@page.descendants': /cards
    order:
        by: date
        dir: desc
    limit: 50
    pagination: true
---
```

![image](https://github.com/khanduras/grav-theme-cardstack/assets/81115927/7e247c20-b061-45bf-95d9-c678a1160049)

Any idea ?

Thanks
