### ISSUE TITLE
pages only shows loading

### ISSUE THREAD

**Issue by k1ngf15h3r** [khanduras/grav-theme-cardstack#5]
only get the loading sign when I start a fresh grav project with the newest release of this theme. had updated permissions and activated twig rendering. when I click the "Back" button in the theme I get a Runtime Exception

**Comment by yrrad** [comment]
Same here. Cardstack v. 1.1.3 Grav Core + Admin v. 1.0.10. Endless loading, no single entry in error log. Browser Edge, IE, Chrome all the same results. Fresh grav install + cardstack. All other themes, including default antimatter, work as hell. Any ideas?

**Comment by k1ngf15h3r** [comment]
Make sure your _Default.md_ in **01.frontpage** look like this

```
---
title: Index
cards:
    items:
        '@page.descendants': /cards
    order:
        by: date
        dir: desc
    limit: 50
    pagination: true
---
```
