### ISSUE TITLE
Skeleton package

### ISSUE THREAD

**Issue by pithp** [khanduras/grav-theme-cardstack#8]
Hi,
I'm trying to test your theme cause I found it very cool in the demo but I can't make it work. I have these issues :
- the file structure mentioned in the Readme.md is not the is not identical to the one in the demo folder so I'm not sure how to set them down and what grav options to use
- when I point out to a page, the navbar shows and then an endless loading starts

So, can you provide a working skeleton package.
Regards
Pit

**Comment by Benderz** [comment]
I have same - endless loading.

**Comment by dviciano** [comment]
The same. Endless loading

**Comment by jduerr** [comment]
yapp - me, too. Endless loading. Categories in navbar from demo folder show just fine though...
**Edit:**

Solution was already in [#5 ](https://github.com/khanduras/grav-theme-cardstack/issues/5)

Thanx k1ngf15h3r!

> k1ngf15h3r commented on 30 Jun
> Make sure your Default.md in 01.frontpage look like this

```

---
title: Index
cards:
    items:
        '@page.descendants': /cards
    order:
        by: date
        dir: desc
    limit: 50
    pagination: true
---
```
